apm-server:
  host: "0.0.0.0:8200"
  # rum:
  #   source_mapping:
  #     elasticsearch:
  #     hosts: ["localhost:9200"]
  #     username: "elastic"
  #     password: "changeme"
output:
  elasticsearch:
    enabled: true
    hosts: ["elasticsearch:9200"]
    username: "elastic"
    password: "changeme"
